= RoboDucks

link:http://roboducks.htl-leonding.ac.at/[Roboducks on HTL-Leonding]

The `RoboDucks` are a team consisting of mainly 3rd- to 5th-grade Students from the HTL-Leonding developing software to participate in the link:https://spl.robocup.org/[Robocup Standard Platform League].

Even tough we are building on code provided by the link:https://hulks.de[HULKs Team] from the Hamburg Univserity of Technology, we create most of our code on our own and try to enhance existing Algorithms and try out new and innovative Approaches.

We would have taken part in the 2020 link:https://robocupgermanopen.de/en/major/spl[RoboCup German Open] but that was rendered impossible by the COVID-19-Pandemic.

== Team

.Supervisors
- link:https://github.com/Bauepete[Prof. Peter Bauer]

.Initial
- Viktoria Streibl
- Melanie Mühleder
- Sabine Woswasih

.2018ers
- link:https://github.com/JanNeuburger[Jan Neuburger]
- link:https://github.com/Bauepete[Florian Schwarcz]
- link:https://github.com/Maxwahl[Maximilian Wahl]
- link:https://github.com/ErikMayrhofer[Erik Mayrhofer]

.2020ers
- link:https://github.com/EminaSljivic[Emina Sljivic]
- link:https://github.com/Marc-Kruiss[Marc Kruiss]
- link:https://github.com/MathiasBal[Mathias Bal]
- link:https://github.com/PhilippEdlinger[Edlinger Philipp]
- link:https://github.com/QuirinEcker[Quirin Ecker]
- link:https://github.com/robertFreiseisen[Robert Freiseisen]
- link:https://github.com/simonholzapfel[Simon Holzapfel]
- link:https://github.com/Primetzvan[Vanessa Primetzhofer]

= Quickstart

== Usage of `Midas`
The central tool when developing RoboDucks-Code is the midas-script.

``` bash
scripts/midas -h
```

A usual upload will look something like this

```bash
scripts/midas upload -e develop nao6 <1>
```
(1) `-e` means: Execute when uploaded completely.

.Useful things
. If you get an error that the PID is locked (aka the program is already running), then you can use `midas kill`
. If you just want to start the program use `midas start`

=== Compile and Upload
There are several "targets", each describing a possible device which we can build the code for.

.Targets
. SimRobot " `simrobot` "
. Nao V5 " `nao5` "
. Nao V6 " `nao6` "

There are several "build types", each describing a set of configs and variables set in the
environment.

.Build Types
. `debug`: Include debug symbols. Only for use with `gdb` or radare2.
. `develop`: Don't include debug symbols, but include certain Prints and Debug-Code. For use with Mate
. `release`: Fastest. Don't use any debug stuff.

```bash
scripts/midas upload -e [build type] [target] [address]
```
.Useful things
. `-c` Uploads with config
. `-n` Uploads without compiling
. `-e` Executes the code after uploading

WARNING: If you experience a *very* slow performance (in Mate or even on the field) or tremendous
upload times due to file sizes (e.G 100MB) you are probably compiling for debug. Don't do this if
you don't have to.

NOTE: If you are annoyed by having to type in your *password* every time, simply upload the ssh-key
with the `midas touch` script.

NOTE: If you have any questions regarding midas or think that the tool is not documented enough,
please consult link:https://github.com/ErikMayrhofer[Erik Mayrhofer] or link:https://github.com/EminaSljivic[Emina Sljivic].

== Hulks
We build on top of code from the hulks-team.

- [HULKs Website](https://hulks.de)
- [Team Research Report 2018](https://www.hulks.de/_files/TRR_2018.pdf)
- [Robotic Hamburg Open Workshop](https://www.rohow.de/)
