name: MateEnv
channels:
  - conda-forge
  - pypi
  - pytorch
dependencies:
  - python=3.6
  - setproctitle=1.1.10
  - pyside2=5.13.1
  - opencv=4.1.2
  - transforms3d=0.3.1
  - pyqtgraph=0.10.0
  - scipy=1.2.1
  - qdarkstyle=2.7
